document.writeln("");
document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("  <meta charset=\'UTF-8\'>");
document.writeln("  <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("  <title>宏达生物联系页面 - 官网 miyao.in</title>");
document.writeln("  <link rel=\'stylesheet\' href=\'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\'>");
document.writeln("");
document.writeln("  <style>");
document.writeln("    /* Reset some default styles */");
document.writeln("    body, h1, h2, h3, p {");
document.writeln("      margin: 0;");
document.writeln("      padding: 0;");
document.writeln("      box-sizing: border-box;");
document.writeln("    }");
document.writeln("");
document.writeln("    /* Global Styles */");
document.writeln("    body {");
document.writeln("      font-family: \'Arial\', sans-serif;");
document.writeln("      background-color: #f4f4f4; /* Light background color */");
document.writeln("      color: #333; /* Text color */");
document.writeln("      line-height: 1.6;");
document.writeln("    }");
document.writeln("");
document.writeln("    container {");
document.writeln("      max-width: 1200px;");
document.writeln("      margin: 0 auto;");
document.writeln("      padding: 20px;");
document.writeln("    }");
document.writeln("");
document.writeln("    /* Header Styles */");
document.writeln("    header {");
document.writeln("      background-color: #2c3e50; /* Dark blue-gray background color */");
document.writeln("      color: #ecf0f1; /* Light text color */");
document.writeln("      padding: 20px 0;");
document.writeln("      text-align: center;");
document.writeln("    }");
document.writeln("");
document.writeln("    header img {");
document.writeln("      width: 50px;");
document.writeln("      height: 50px;");
document.writeln("      border-radius: 50%;");
document.writeln("      margin-right: 10px;");
document.writeln("      vertical-align: middle;");
document.writeln("    }");
document.writeln("");
document.writeln("    header h1 {");
document.writeln("      font-size: 36px;");
document.writeln("      margin-bottom: 10px;");
document.writeln("    }");
document.writeln("");
document.writeln("    nav ul {");
document.writeln("      list-style-type: none;");
document.writeln("      display: flex;");
document.writeln("      justify-content: center;");
document.writeln("      margin-top: 20px;");
document.writeln("    }");
document.writeln("");
document.writeln("    nav ul li {");
document.writeln("      margin-right: 20px;");
document.writeln("    }");
document.writeln("");
document.writeln("    nav ul li:last-child {");
document.writeln("      margin-right: 0;");
document.writeln("    }");
document.writeln("");
document.writeln("    nav ul li a {");
document.writeln("      color: #ecf0f1;");
document.writeln("      text-decoration: none;");
document.writeln("      font-weight: 500;");
document.writeln("    }");
document.writeln("");
document.writeln("    /* Section Styles */");
document.writeln("    section {");
document.writeln("      padding: 40px 0;");
document.writeln("      text-align: center;");
document.writeln("    }");
document.writeln("");
document.writeln("    section h2 {");
document.writeln("      font-size: 28px;");
document.writeln("      margin-bottom: 20px;");
document.writeln("      color: #333;");
document.writeln("    }");
document.writeln("");
document.writeln("    .directory {");
document.writeln("      display: grid;");
document.writeln("      grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));");
document.writeln("      grid-gap: 20px;");
document.writeln("      justify-items: center;");
document.writeln("    }");
document.writeln("");
document.writeln("    .directory-item {");
document.writeln("      background-color: #fff;");
document.writeln("      padding: 20px;");
document.writeln("      border-radius: 8px;");
document.writeln("      text-align: center;");
document.writeln("      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);");
document.writeln("      transition: transform 0.3s, box-shadow 0.3s;");
document.writeln("    }");
document.writeln("");
document.writeln("    .directory-item:hover {");
document.writeln("      transform: scale(1.02);");
document.writeln("      box-shadow: 0 0 20px rgba(0, 0, 0, 0.2);");
document.writeln("    }");
document.writeln("");
document.writeln("    /* Footer Styles */");
document.writeln("    footer {");
document.writeln("      background-color: #2c3e50;");
document.writeln("      color: #ecf0f1;");
document.writeln("      padding: 20px 0;");
document.writeln("      text-align: center;");
document.writeln("    }");
document.writeln("");
document.writeln("    footer ul {");
document.writeln("      list-style-type: none;");
document.writeln("      margin-top: 20px;");
document.writeln("    }");
document.writeln("");
document.writeln("    footer ul li {");
document.writeln("      display: inline;");
document.writeln("      margin-right: 20px;");
document.writeln("    }");
document.writeln("");
document.writeln("    footer ul li:last-child {");
document.writeln("      margin-right: 0;");
document.writeln("    }");
document.writeln("");
document.writeln("    footer ul li a {");
document.writeln("      color: #ecf0f1;");
document.writeln("      text-decoration: none;");
document.writeln("      font-weight: 500;");
document.writeln("    }");
document.writeln("  </style>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("  <header>");
document.writeln("    <container>");
document.writeln("      <img src=\'https://tawk.link/5eb2d148a1bad90e54a240c0/kb/logo/eZnJN69tGF.jpg\' alt=\'宏达生物 Logo\'>");
document.writeln("      <h1>宏达生物联系页面</h1>");
document.writeln("      <nav>");
document.writeln("        <ul>");
document.writeln("          <li><a href=\'https://miyao.in\'><i class=\'fas fa-info-circle\'></i> 牢记官网 miyao.in</a></li>");
document.writeln("          <li><a href=\'https://miyaocn.tawk.help/article/%E5%85%B3%E4%BA%8E%E6%88%91%E4%BB%AC%E5%BB%BA%E8%AE%AE-%E8%B4%AD%E4%B9%B0%E6%8C%87%E5%8D%97%E9%98%B2%E9%AA%97%E6%8A%80%E5%B7%A7%E3%80%82\'><i class=\'fas fa-headset\'></i> 教程和防骗指南</a></li>");
document.writeln("          <li><a href=\'https://tawk.to/chat/5eb2d148a1bad90e54a240c0/default\'><i class=\'fas fa-headset\'></i> 在线客服</a></li>");
document.writeln("          <li><a href=\'https://github.com/potatogm/potato/releases\'><i class=\'fas fa-headset\'></i> potato下载</a></li>");
document.writeln("        </ul>");
document.writeln("      </nav>");
document.writeln("    </container>");
document.writeln("  </header>");
document.writeln("");
document.writeln("");
document.writeln("  <container>");
document.writeln("    <section id=\'about\'>");
document.writeln("      <h2>关于我们</h2>");
document.writeln("      <p>宏达生物是一家七年信誉保证的公司，我们支持视频看货，但不支持货到付款。请通过官网<a href=\'https://miyao.in\'>miyao.in</a>购买我们的产品。</p>");
document.writeln("    </section>");
document.writeln("");
document.writeln("    <section id=\'faq\'>");
document.writeln("      <h2>常见问题</h2>");
document.writeln("      <div class=\'directory\'>");
document.writeln("        <div class=\'directory-item\'>");
document.writeln("          <h3>如何付款?</h3>");
document.writeln("          <p>目前仅支持虚拟货币付款，你可以从正规交易所购买btc或者usdt后和我们交易！</p>");
document.writeln("        </div>");
document.writeln("        <div class=\'directory-item\'>");
document.writeln("          <h3>如何看货?</h3>");
document.writeln("          <p>我们的产品在potato的频道里面，类似微信的公众号。里面有实拍的产品图片介绍和价格！</p>");
document.writeln("        </div>");
document.writeln("        <div class=\'directory-item\'>");
document.writeln("          <h3>我如何收货?</h3>");
document.writeln("          <p>交易完成后，我们会通过正规产品给你发货，带有物流信息一起发给你，并告知你我们的产品藏在正规产品的那里。只为保证你我的安全，生意能长久！</p>");
document.writeln("        </div>");
document.writeln("        <div class=\'directory-item\'>");
document.writeln("          <h3>我是国外用户可以购买吗?</h3>");
document.writeln("          <p>目前我们的主要销售渠道是大陆，非大陆地区，我们收260元的中介费，给你下单安全可靠的合作的别的供应商！</p>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </section>");
document.writeln("");
document.writeln("    <section id=\'contact\'>");
document.writeln("      <h2>联系方式</h2>");
document.writeln("      <p>potato：miyaoin</p>");
document.writeln("      <p>点击下面的链接访问potato联系页面：<a href=\'https://pzcp.org/miyaoin\'>miyaoin</a></p>");
document.writeln("      <p>电报频道：<a href=\'https://t.me/s/miyaocn/\'>电报频道</a></p>");
document.writeln("   ");
document.writeln("      <p>请尽量使用potato联系我们，我们不在支持微信,QQ等国内交流工具！</p>");
document.writeln("    </section>");
document.writeln("");
document.writeln("    <section id=\'customer-support\'>");
document.writeln("      <h2>potato软件官网和如何购买虚拟货币教程</h2>");
document.writeln("      <div class=\'directory\'>");
document.writeln("        <div class=\'directory-item\'>");
document.writeln("          <h3>代理推荐</h3>");
document.writeln("          <p><a href=\'https://github.com/LetsGo666/LetsGo_11/blob/main/\'>快连代理</a></p>");
document.writeln("          <p><a href=\'https://dh.cutecloud.link/\'>最萌云机场</a></p>");
document.writeln("        </div>");
document.writeln("        <div class=\'directory-item\'>");
document.writeln("          <h3>交易所购买btc教程</h3>");
document.writeln("          <p><a href=\'https://yueqcaiji.notion.site/yueqcaiji/Binance-2022-bb20128d670441acbce6c3b341dd8602\'>中国大陆用户Binance币安注册教程(2023最新)</a></p>");
document.writeln("        </div>");
document.writeln("        <div class=\'directory-item\'>");
document.writeln("          <h3>OKx歐易交易平台注册教程</h3>");
document.writeln("          <p><a href=\'https://yueqcaiji.notion.site/yueqcaiji/Binance-2022-bb20128d670441acbce6c3b341dd8602\'>中国大陆用户OKx歐易交易平台注册教程(2023最新)</a></p>");
document.writeln("        </div>");
document.writeln("        <div class=\'directory-item\'>");
document.writeln("          <h3>建议和防骗指南</h3>");
document.writeln("          <p><a href=\'https://miyaocn.tawk.help/article/%E5%85%B3%E4%BA%8E%E6%88%91%E4%BB%AC%E5%BB%BA%E8%AE%AE-%E8%B4%AD%E4%B9%B0%E6%8C%87%E5%8D%97%E9%98%B2%E9%AA%97%E6%8A%80%E5%B7%A7%E3%80%82\'>建议和防骗指南</a></p>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </section>");
document.writeln("  </container>");
document.writeln("");
document.writeln("  <footer>");
document.writeln("    <container>");
document.writeln("      <ul>");
document.writeln("        <li><a href=\'#\'>隐私政策</a></li>");
document.writeln("        <li><a href=\'#\'>服务条款</a></li>");
document.writeln("        <li><a href=\'#\'>网站地图</a></li>");
document.writeln("      </ul>");
document.writeln("      <p>&copy; 2023 宏达生物. 版权所有。</p>");
document.writeln("    </container>");
document.writeln("  </footer>");
document.writeln("</body>");
document.writeln("</html>");
document.writeln("");
